apiVersion: v1
kind: Service # Exposing q network application running as one or more Pods in the Cluster
metadata: # Data that helps uniquely identify the object
  name: bankati-front
spec:
  selector: # The set of pods targeted by the Service
    app: bankati-front # Needs to match deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30101
  type: NodePort  # Exposes the service externally using a load balancer
