apiVersion: apps/v1
kind: Deployment # The kind of object we want to create
metadata: # Data that helps uniquely identify the object
  name: bankati-front
spec: # Set the desired state of our deployment
  replicas: 1 # Number of the pods
  selector:
    matchLabels:
      app: bankati-front
  template:
    metadata:
      labels:
        app: bankati-front
    spec: # Desired state of the pod
      containers:
      - name: bankati-front
        image: soukaina915/bankati-front:9
        ports:
        - containerPort: 80
